name: Generate and Build Docs

on:
  push:
    branches: [ master ]
    paths:
      - 'packages/docs/**'
      - '.github/workflows/generate-docs.yml'
      - 'typedoc.json'
      - 'packages/pdf-sign-kit/src/types.ts'
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Node
        uses: actions/setup-node@v4        
        with:          
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Generate API docs (Typedoc)
        run: npm run docs:gen

      - name: Build docs (VitePress)
        run: npm run build:docs

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
