name: Validate - Run tests and checks on PRs

on:
  workflow_dispatch:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  tests:
    uses: ./.github/workflows/reusable-tests.yml
    with:      
      run-e2e: true